version: "3.9"

services:
  web:
    build: .
    container_name: dgp_web
    env_file: .env
    ports:
      - "5000:5000"
    restart: unless-stopped
    depends_on:
      - redis

  worker:
    build: .
    container_name: dgp_worker
    env_file: .env
    command: celery -A dgp_intra.celery_app worker --loglevel=info
    restart: unless-stopped
    depends_on:
      - redis

  beat:
    build: .
    container_name: dgp_beat
    env_file: .env
    command: celery -A dgp_intra.celery_app beat --loglevel=info
    restart: unless-stopped
    depends_on:
      - redis

  redis:
    image: redis:7
    container_name: dgp_redis
    restart: unless-stopped
