"""Add tomorrow forecast system

Revision ID: 2ef2280badd9
Revises: 7a518638c348
Create Date: 2025-12-12 09:23:22.298094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ef2280badd9'
down_revision: Union[str, None] = '7a518638c348'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_arrival_forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('expected_arrivals', sa.Integer(), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('daily_arrival_forecasts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_arrival_forecasts_date'), ['date'], unique=True)

    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checking_out_tomorrow', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_column('checking_out_tomorrow')

    with op.batch_alter_table('daily_arrival_forecasts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_arrival_forecasts_date'))

    op.drop_table('daily_arrival_forecasts')
    # ### end Alembic commands ###
