"""Add saturday and sunday to patients menu

Revision ID: 4271e9aed2d0
Revises: 6e6519ecbdf2
Create Date: 2025-12-08 09:05:53.506527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4271e9aed2d0'
down_revision: Union[str, None] = '6e6519ecbdf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients_menu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('saturday', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('sunday', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('saturday_dinner', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('sunday_dinner', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients_menu', schema=None) as batch_op:
        batch_op.drop_column('sunday_dinner')
        batch_op.drop_column('saturday_dinner')
        batch_op.drop_column('sunday')
        batch_op.drop_column('saturday')

    # ### end Alembic commands ###
