"""empty message

Revision ID: 6e6519ecbdf2
Revises: f35eefe9f93a
Create Date: 2025-11-25 15:01:28.269965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6e6519ecbdf2'
down_revision: Union[str, None] = 'f35eefe9f93a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('breakfast_registration', schema=None) as batch_op:
        batch_op.drop_constraint('fk_breakfast_user', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_constraint('fk_event_organizer', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['organizer_id'], ['id'])

    with op.batch_alter_table('event_registration', schema=None) as batch_op:
        batch_op.drop_constraint('fk_eventreg_event', type_='foreignkey')
        batch_op.drop_constraint('fk_eventreg_user', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'event', ['event_id'], ['id'])

    with op.batch_alter_table('lunch_registration', schema=None) as batch_op:
        batch_op.drop_constraint('fk_lunch_user', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('patients_menu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monday_dinner', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('tuesday_dinner', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('wednesday_dinner', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('thursday_dinner', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('friday_dinner', sa.String(length=200), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_admin',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('credit',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('owes',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('vacation', schema=None) as batch_op:
        batch_op.drop_constraint('fk_vacation_user', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vacation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_vacation_user', 'user', ['user_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('owes',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('credit',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('is_admin',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('patients_menu', schema=None) as batch_op:
        batch_op.drop_column('friday_dinner')
        batch_op.drop_column('thursday_dinner')
        batch_op.drop_column('wednesday_dinner')
        batch_op.drop_column('tuesday_dinner')
        batch_op.drop_column('monday_dinner')

    with op.batch_alter_table('lunch_registration', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_lunch_user', 'user', ['user_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')

    with op.batch_alter_table('event_registration', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_eventreg_user', 'user', ['user_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
        batch_op.create_foreign_key('fk_eventreg_event', 'event', ['event_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_event_organizer', 'user', ['organizer_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')

    with op.batch_alter_table('breakfast_registration', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_breakfast_user', 'user', ['user_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')

    # ### end Alembic commands ###
