"""Add meal registration system

Revision ID: 7a518638c348
Revises: 5101a32a0d0e
Create Date: 2025-12-11 11:07:59.066800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a518638c348'
down_revision: Union[str, None] = '5101a32a0d0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meal_registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('meal_type', sa.Enum('BREAKFAST', 'LUNCH', 'DINNER', name='mealtype'), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('people_count', sa.Integer(), nullable=False),
    sa.Column('patients_count', sa.Integer(), nullable=False),
    sa.Column('relatives_count', sa.Integer(), nullable=False),
    sa.Column('registered_by_id', sa.Integer(), nullable=False),
    sa.Column('registered_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['registered_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id', 'meal_type', 'date', name='unique_meal_registration')
    )
    with op.batch_alter_table('meal_registrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meal_registrations_date'), ['date'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal_registrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meal_registrations_date'))

    op.drop_table('meal_registrations')
    # ### end Alembic commands ###
