"""Ledger feature introduced

Revision ID: b81bd97d94fe
Revises: c6f3c1513c94
Create Date: 2025-10-21 10:33:21.307470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'b81bd97d94fe'
down_revision: Union[str, None] = 'c6f3c1513c94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - adjusted to avoid dropping FK-required indexes ###
    op.create_table(
        'credit_transaction',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('posted_at', sa.DateTime(), nullable=True),
        sa.Column('delta_credits', sa.Integer(), nullable=False),
        sa.Column('tx_type', sa.Enum('PURCHASE', 'SPEND', 'ADJUSTMENT', 'REFUND', name='txtype'), nullable=False),
        sa.Column('status', sa.Enum('PENDING', 'POSTED', 'CANCELED', name='txstatus'), nullable=False),
        sa.Column('amount_dkk_ore', sa.Integer(), nullable=True),
        sa.Column('source', sa.String(length=64), nullable=True),
        sa.Column('created_by_id', sa.Integer(), nullable=True),
        sa.Column('note', sa.String(length=280), nullable=True),
        sa.CheckConstraint('delta_credits <> 0', name='ck_tx_nonzero_delta'),
        sa.ForeignKeyConstraint(['created_by_id'], ['user.id']),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_credit_transaction_created_at'), 'credit_transaction', ['created_at'], unique=False)
    op.create_index(op.f('ix_credit_transaction_status'), 'credit_transaction', ['status'], unique=False)
    op.create_index(op.f('ix_credit_transaction_tx_type'), 'credit_transaction', ['tx_type'], unique=False)
    op.create_index(op.f('ix_credit_transaction_user_id'), 'credit_transaction', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - adjusted to only undo what's new ###
    op.drop_index(op.f('ix_credit_transaction_user_id'), table_name='credit_transaction')
    op.drop_index(op.f('ix_credit_transaction_tx_type'), table_name='credit_transaction')
    op.drop_index(op.f('ix_credit_transaction_status'), table_name='credit_transaction')
    op.drop_index(op.f('ix_credit_transaction_created_at'), table_name='credit_transaction')
    op.drop_table('credit_transaction')
    # ### end Alembic commands ###
