"""Add PatientsMenu model

Revision ID: f35eefe9f93a
Revises: b81bd97d94fe
Create Date: 2025-11-21 13:13:01.535238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f35eefe9f93a'
down_revision: Union[str, None] = 'b81bd97d94fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


"""Add PatientsMenu model

Revision ID: f35eefe9f93a
Revises: b81bd97d94fe
Create Date: 2025-11-21 13:13:01.535238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f35eefe9f93a'
down_revision: Union[str, None] = 'b81bd97d94fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients_menu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week', sa.String(length=10), nullable=True),
    sa.Column('monday', sa.String(length=200), nullable=True),
    sa.Column('tuesday', sa.String(length=200), nullable=True),
    sa.Column('wednesday', sa.String(length=200), nullable=True),
    sa.Column('thursday', sa.String(length=200), nullable=True),
    sa.Column('friday', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('breakfast_registration', schema=None) as batch_op:
        batch_op.drop_index('idx_breakfast_user')
        batch_op.drop_constraint('fk_breakfast_user', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_index('idx_event_date')
        batch_op.drop_index('idx_event_organizer')
        batch_op.drop_constraint('fk_event_organizer', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['organizer_id'], ['id'])

    with op.batch_alter_table('event_registration', schema=None) as batch_op:
        batch_op.drop_index('idx_eventreg_event')
        batch_op.drop_index('idx_eventreg_user')
        batch_op.drop_constraint('fk_eventreg_event', type_='foreignkey')
        batch_op.drop_constraint('fk_eventreg_user', type_='foreignkey')
        batch_op.create_foreign_key(None, 'event', ['event_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('lunch_registration', schema=None) as batch_op:
        batch_op.drop_index('idx_lunch_date')
        batch_op.drop_index('idx_lunch_user')
        batch_op.drop_constraint('fk_lunch_user', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_admin',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('credit',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('owes',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('vacation', schema=None) as batch_op:
        batch_op.drop_index('idx_vacation_range')
        batch_op.drop_index('idx_vacation_user')
        batch_op.drop_constraint('fk_vacation_user', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vacation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_vacation_user', 'user', ['user_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
        batch_op.create_index('idx_vacation_user', ['user_id'], unique=False)
        batch_op.create_index('idx_vacation_range', ['start_date', 'end_date'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('owes',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('credit',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('is_admin',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('lunch_registration', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_lunch_user', 'user', ['user_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
        batch_op.create_index('idx_lunch_user', ['user_id'], unique=False)
        batch_op.create_index('idx_lunch_date', ['date'], unique=False)

    with op.batch_alter_table('event_registration', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_eventreg_user', 'user', ['user_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
        batch_op.create_foreign_key('fk_eventreg_event', 'event', ['event_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_index('idx_eventreg_user', ['user_id'], unique=False)
        batch_op.create_index('idx_eventreg_event', ['event_id'], unique=False)

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_event_organizer', 'user', ['organizer_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
        batch_op.create_index('idx_event_organizer', ['organizer_id'], unique=False)
        batch_op.create_index('idx_event_date', ['date'], unique=False)

    with op.batch_alter_table('breakfast_registration', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_breakfast_user', 'user', ['user_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
        batch_op.create_index('idx_breakfast_user', ['user_id'], unique=False)

    op.drop_table('patients_menu')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patients_menu')
    # ### end Alembic commands ###